version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo "Starting Docker daemon..."
      - nohup /usr/local/bin/dockerd-entrypoint.sh &>/tmp/docker.log &
      - timeout 15 sh -c "until docker info; do sleep 1; done"
      - echo "Docker is ready."

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

  build:
    commands:
      - echo "Building Docker image..."
      - docker buildx build --platform linux/amd64 -f ./backend/Dockerfile.prod -t $IMAGE_REPO_NAME:latest ./backend --load
      - docker tag $IMAGE_REPO_NAME:latest $ECR_REGISTRY/$IMAGE_REPO_NAME:latest

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $ECR_REGISTRY/$IMAGE_REPO_NAME:latest
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $ECR_REGISTRY/$IMAGE_REPO_NAME:latest > imagedefinitions.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
