name: Destroy Pipeline

on:
  schedule:
    - cron: "0 7 * * *" # 5PM AEST
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Create terraform.tfvars
        run: |
          cat <<EOF > devops/terraform.tfvars
          ${{ secrets.TERRAFORM_VARIABLES }}
          EOF

      - name: Run destroy script
        run: |
          cd ./devops
          chmod +x destroy.sh
          ./destroy.sh
